package languages

import (
	"fmt"
	"strings"
)

// CTemplate C模板
type CTemplate struct{}

func (t *CTemplate) GetFileExtension() string     { return ".c" }
func (t *CTemplate) GetActivityFileName() string  { return "activity.c" }
func (t *CTemplate) GetLanguageName() string      { return "C" }

func (t *CTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	_ = fmt.Sprintf("contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

#include <stdio.h>
#include <string.h>

typedef struct {
    char date[11];
    int commit_number;
    int total_commits;
} Contribution;

Contribution create_contribution() {
    Contribution c;
    strcpy(c.date, "%s");
    c.commit_number = %d;
    c.total_commits = %d;
    return c;
}

void print_contribution(Contribution* c) {
    printf("Contribution on %%s (%%d/%%d)\n", 
           c->date, c->commit_number, c->total_commits);
}

int main() {
    Contribution contribution = create_contribution();
    print_contribution(&contribution);
    return 0;
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *CTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA C project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated C contribution records.\n\n## Structure\n\n- `src/` - C source files\n- `Makefile` - Build configuration\n- `README.md` - This file\n\n## Build\n\n```bash\nmake\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *CTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"Makefile": `CC=gcc
CFLAGS=-Wall -Wextra -std=c11
SRC=$(wildcard src/*.c)
OBJ=$(SRC:.c=.o)
TARGET=program

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -f $(OBJ) $(TARGET)

.PHONY: all clean
`,
		".gitignore": `# C
*.o
*.obj
*.exe
*.out
*.app
program

# IDE
.vscode/
.idea/
*.swp
`,
	}
}
