package languages

import (
	"fmt"
	"strings"
)

// CppTemplate C++模板
type CppTemplate struct{}

func (t *CppTemplate) GetFileExtension() string     { return ".cpp" }
func (t *CppTemplate) GetActivityFileName() string  { return "activity.cpp" }
func (t *CppTemplate) GetLanguageName() string      { return "C++" }

func (t *CppTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	className := fmt.Sprintf("Contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

#include <string>
#include <iostream>

class %s {
private:
    std::string date;
    int commitNumber;
    int totalCommits;

public:
    %s() : date("%s"), commitNumber(%d), totalCommits(%d) {}
    
    std::string getDate() const { return date; }
    int getCommitNumber() const { return commitNumber; }
    int getTotalCommits() const { return totalCommits; }
    
    std::string getInfo() const {
        return "Contribution on " + date + " (" + 
               std::to_string(commitNumber) + "/" + 
               std::to_string(totalCommits) + ")";
    }
};

int main() {
    %s contribution;
    std::cout << contribution.getInfo() << std::endl;
    return 0;
}
`, date, commitNum, totalCommits, className, className, date, commitNum, totalCommits, className)
}

func (t *CppTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA C++ project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated C++ contribution records.\n\n## Structure\n\n- `src/` - C++ source files\n- `CMakeLists.txt` - CMake build configuration\n- `README.md` - This file\n\n## Build\n\n```bash\nmkdir build && cd build\ncmake ..\nmake\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *CppTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"CMakeLists.txt": fmt.Sprintf(`cmake_minimum_required(VERSION 3.10)
project(%s)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

file(GLOB SOURCES "src/*.cpp")
add_executable(${PROJECT_NAME} ${SOURCES})
`, repoName),
		".gitignore": `# C++
*.o
*.obj
*.exe
*.out
*.app
build/
cmake-build-*/

# IDE
.vscode/
.idea/
*.swp
`,
	}
}
