package languages

import (
	"fmt"
	"strings"
)

// CSharpTemplate C#模板
type CSharpTemplate struct{}

func (t *CSharpTemplate) GetFileExtension() string     { return ".cs" }
func (t *CSharpTemplate) GetActivityFileName() string  { return "Activity.cs" }
func (t *CSharpTemplate) GetLanguageName() string      { return "C#" }

func (t *CSharpTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	className := fmt.Sprintf("Contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

using System;

namespace GreenWall.Contributions
{
    public class %s
    {
        public string Date { get; } = "%s";
        public int CommitNumber { get; } = %d;
        public int TotalCommits { get; } = %d;

        public string GetInfo()
        {
            return $"Contribution on {Date} ({CommitNumber}/{TotalCommits})";
        }

        public override string ToString()
        {
            return GetInfo();
        }
    }
}
`, date, commitNum, totalCommits, className, date, commitNum, totalCommits)
}

func (t *CSharpTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA C# project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated C# contribution records.\n\n## Structure\n\n- `src/` - C# source files\n- `%s.csproj` - Project file\n- `README.md` - This file\n\n## Build\n\n```bash\ndotnet build\n```\n\n## License\n\nMIT License\n", repoName, repoName)
}

func (t *CSharpTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		repoName + ".csproj": `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
`,
		".gitignore": `# C#
bin/
obj/
*.user
*.suo
*.cache

# IDE
.vscode/
.idea/
`,
	}
}
