package languages

import (
	"fmt"
)

// CSSTemplate CSS模板
type CSSTemplate struct{}

func (t *CSSTemplate) GetFileExtension() string     { return ".css" }
func (t *CSSTemplate) GetActivityFileName() string  { return "style.css" }
func (t *CSSTemplate) GetLanguageName() string      { return "CSS" }

func (t *CSSTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`/* 
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

.contribution-%s-%d {
    display: block;
    content: "Contribution %d/%d";
    background-color: #f6f8fa;
    border: 1px solid #d1d5da;
    border-radius: 3px;
    padding: 8px 16px;
    margin: 8px 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}

.contribution-%s-%d::before {
    content: "%s";
    font-weight: bold;
    color: #24292e;
}
`, date, commitNum, totalCommits, date, commitNum, commitNum, totalCommits, date, commitNum, date)
}

func (t *CSSTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA CSS project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated CSS contribution records.\n\n## Structure\n\n- `styles/` - CSS files\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *CSSTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		".gitignore": `.DS_Store
.vscode/
.idea/
`,
	}
}
