package languages

import (
	"fmt"
)

// GoTemplate Go模板
type GoTemplate struct{}

func (t *GoTemplate) GetFileExtension() string     { return ".go" }
func (t *GoTemplate) GetActivityFileName() string  { return "activity.go" }
func (t *GoTemplate) GetLanguageName() string      { return "Go" }

func (t *GoTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`package contributions

import "fmt"

// Contribution represents a contribution record for %s
// Commit %d of %d
// Generated by GreenWall
type Contribution struct {
	Date          string
	CommitNumber  int
	TotalCommits  int
}

// NewContribution creates a new contribution instance
func NewContribution() *Contribution {
	return &Contribution{
		Date:         "%s",
		CommitNumber: %d,
		TotalCommits: %d,
	}
}

// GetInfo returns the contribution information
func (c *Contribution) GetInfo() string {
	return fmt.Sprintf("Contribution on %%s (%%d/%%d)", c.Date, c.CommitNumber, c.TotalCommits)
}

// String implements the Stringer interface
func (c *Contribution) String() string {
	return c.GetInfo()
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *GoTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Go project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Go contribution records.\n\n## Structure\n\n- `contributions/` - Go package with contribution records\n- `go.mod` - Go module file\n- `README.md` - This file\n\n## Installation\n\n```bash\ngo mod download\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *GoTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"go.mod": fmt.Sprintf(`module github.com/greenwall/%s

go 1.21
`, repoName),
		".gitignore": `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output
*.out

# Go workspace
go.work

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
`,
	}
}
