package languages

import (
	"fmt"
)

// HTMLTemplate HTML模板
type HTMLTemplate struct{}

func (t *HTMLTemplate) GetFileExtension() string     { return ".html" }
func (t *HTMLTemplate) GetActivityFileName() string  { return "activity.html" }
func (t *HTMLTemplate) GetLanguageName() string      { return "HTML" }

func (t *HTMLTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contribution Record</title>
    <style>
        .contribution {
            font-family: sans-serif;
            border: 1px solid #e1e4e8;
            padding: 20px;
            margin: 20px;
            border-radius: 6px;
            background-color: #fafbfc;
        }
        .meta { color: #586069; }
    </style>
</head>
<body>
    <div class="contribution">
        <h2>Contribution on %s</h2>
        <div class="meta">
            <span>Commit %d of %d</span>
        </div>
        <p>Generated by GreenWall</p>
    </div>
</body>
</html>
`, date, commitNum, totalCommits)
}

func (t *HTMLTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nAn HTML project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated HTML contribution records.\n\n## Structure\n\n- `public/` - HTML files\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *HTMLTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		".gitignore": `.DS_Store
.vscode/
.idea/
`,
	}
}
