package languages

import (
	"fmt"
)

// JavaScriptTemplate JavaScript模板
type JavaScriptTemplate struct{}

func (t *JavaScriptTemplate) GetFileExtension() string     { return ".js" }
func (t *JavaScriptTemplate) GetActivityFileName() string  { return "activity.js" }
func (t *JavaScriptTemplate) GetLanguageName() string      { return "JavaScript" }

func (t *JavaScriptTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

class Contribution {
  constructor() {
    this.date = '%s';
    this.commitNumber = %d;
    this.totalCommits = %d;
  }

  getInfo() {
    return ` + "`Contribution on ${this.date} (${this.commitNumber}/${this.totalCommits})`" + `;
  }

  toString() {
    return this.getInfo();
  }
}

module.exports = Contribution;

// If running directly
if (require.main === module) {
  const contribution = new Contribution();
  console.log(contribution.getInfo());
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *JavaScriptTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA JavaScript/Node.js project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated JavaScript contribution records.\n\n## Structure\n\n- `src/` - Source files\n- `package.json` - Node.js package configuration\n- `README.md` - This file\n\n## Installation\n\n```bash\nnpm install\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *JavaScriptTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"package.json": fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "description": "Generated with GreenWall",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": ["greenwall", "contributions"],
  "author": "",
  "license": "MIT"
}
`, repoName),
		".gitignore": `node_modules/
npm-debug.log
yarn-error.log
.env
.DS_Store
dist/
build/
.vscode/
.idea/
`,
	}
}
