package languages

import (
	"fmt"
	"strings"
)

// JavaTemplate Java模板
type JavaTemplate struct{}

func (t *JavaTemplate) GetFileExtension() string     { return ".java" }
func (t *JavaTemplate) GetActivityFileName() string  { return "Activity.java" }
func (t *JavaTemplate) GetLanguageName() string      { return "Java" }

func (t *JavaTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	className := fmt.Sprintf("Contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`package com.greenwall.contributions;

/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */
public class %s {
    private String date = "%s";
    private int commitNumber = %d;
    private int totalCommits = %d;
    
    public String getDate() {
        return date;
    }
    
    public int getCommitNumber() {
        return commitNumber;
    }
    
    public int getTotalCommits() {
        return totalCommits;
    }
    
    public String getInfo() {
        return String.format("Contribution on %%s (%%d/%%d)", date, commitNumber, totalCommits);
    }
}
`, date, commitNum, totalCommits, className, date, commitNum, totalCommits)
}

func (t *JavaTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Java project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Java contribution records.\n\n## Structure\n\n- `src/main/java/com/greenwall/contributions/` - Contribution classes\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *JavaTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"pom.xml": fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.greenwall</groupId>
    <artifactId>%s</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>
    
    <name>%s</name>
    <description>Generated with GreenWall</description>
    
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
`, repoName, repoName),
		".gitignore": `target/
*.class
*.jar
*.war
*.ear
.idea/
*.iml
.vscode/
`,
	}
}
