package languages

import (
	"fmt"
	"strings"
)

// KotlinTemplate Kotlin模板
type KotlinTemplate struct{}

func (t *KotlinTemplate) GetFileExtension() string     { return ".kt" }
func (t *KotlinTemplate) GetActivityFileName() string  { return "Activity.kt" }
func (t *KotlinTemplate) GetLanguageName() string      { return "Kotlin" }

func (t *KotlinTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	className := fmt.Sprintf("Contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`package com.greenwall.contributions

/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */
class %s {
    val date = "%s"
    val commitNumber = %d
    val totalCommits = %d
    
    fun getInfo(): String {
        return "Contribution on $date ($commitNumber/$totalCommits)"
    }
}

fun main() {
    val contribution = %s()
    println(contribution.getInfo())
}
`, date, commitNum, totalCommits, className, date, commitNum, totalCommits, className)
}

func (t *KotlinTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Kotlin project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Kotlin contribution records.\n\n## Structure\n\n- `src/main/kotlin/` - Kotlin source files\n- `build.gradle.kts` - Gradle build configuration\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *KotlinTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"build.gradle.kts": `plugins {
    kotlin("jvm") version "1.8.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
}
`,
		".gitignore": `.gradle
/build
.idea/
.vscode/
`,
	}
}
