package languages

import (
	"fmt"
	"strings"
)

// PHPTemplate PHP模板
type PHPTemplate struct{}

func (t *PHPTemplate) GetFileExtension() string     { return ".php" }
func (t *PHPTemplate) GetActivityFileName() string  { return "activity.php" }
func (t *PHPTemplate) GetLanguageName() string      { return "PHP" }

func (t *PHPTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`<?php
/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

class Contribution {
    private $date;
    private $commitNumber;
    private $totalCommits;

    public function __construct() {
        $this->date = "%s";
        $this->commitNumber = %d;
        $this->totalCommits = %d;
    }

    public function getInfo() {
        return sprintf("Contribution on %%s (%%d/%%d)", $this->date, $this->commitNumber, $this->totalCommits);
    }
}

// If running directly
if (php_sapi_name() === 'cli') {
    $contribution = new Contribution();
    echo $contribution->getInfo() . PHP_EOL;
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *PHPTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA PHP project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated PHP contribution records.\n\n## Structure\n\n- `src/` - PHP source files\n- `composer.json` - PHP package configuration\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *PHPTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"composer.json": fmt.Sprintf(`{
    "name": "greenwall/%s",
    "description": "Generated with GreenWall",
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "GreenWall\\": "src/"
        }
    },
    "require": {}
}
`, strings.ToLower(repoName)),
		".gitignore": `vendor/
composer.lock
.env
.idea/
.vscode/
`,
	}
}
