package languages

import (
	"fmt"
	"strings"
)

// PythonTemplate Python模板
type PythonTemplate struct{}

func (t *PythonTemplate) GetFileExtension() string     { return ".py" }
func (t *PythonTemplate) GetActivityFileName() string  { return "activity.py" }
func (t *PythonTemplate) GetLanguageName() string      { return "Python" }

func (t *PythonTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	_ = fmt.Sprintf("contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`"""
Contribution record for %s
Commit %d of %d
Generated by GreenWall
"""

from datetime import datetime


class Contribution:
    """Represents a single contribution record."""
    
    def __init__(self):
        self.date = "%s"
        self.commit_number = %d
        self.total_commits = %d
    
    def get_info(self) -> str:
        """Get contribution information."""
        return f"Contribution on {self.date} ({self.commit_number}/{self.total_commits})"
    
    def __str__(self) -> str:
        return self.get_info()
    
    def __repr__(self) -> str:
        return f"Contribution(date='{self.date}', commit={self.commit_number})"


# Module-level instance
contribution = Contribution()

if __name__ == "__main__":
    print(contribution.get_info())
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *PythonTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Python project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Python contribution records.\n\n## Structure\n\n- `contributions/` - Contribution modules\n- `README.md` - This file\n- `requirements.txt` - Python dependencies\n\n## Installation\n\n```bash\npip install -r requirements.txt\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *PythonTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"requirements.txt": `# Python dependencies
# Add your dependencies here
`,
		"setup.py": fmt.Sprintf(`from setuptools import setup, find_packages

setup(
    name="%s",
    version="1.0.0",
    description="Generated with GreenWall",
    packages=find_packages(),
    python_requires=">=3.7",
)
`, repoName),
		".gitignore": `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
.venv/
venv/
ENV/
.vscode/
.idea/
`,
		"contributions/__init__.py": `"""Contributions package."""
`,
	}
}
