package languages

import (
	"fmt"
)

// RubyTemplate Ruby模板
type RubyTemplate struct{}

func (t *RubyTemplate) GetFileExtension() string     { return ".rb" }
func (t *RubyTemplate) GetActivityFileName() string  { return "activity.rb" }
func (t *RubyTemplate) GetLanguageName() string      { return "Ruby" }

func (t *RubyTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`# Contribution record for %s
# Commit %d of %d
# Generated by GreenWall

class Contribution
  attr_reader :date, :commit_number, :total_commits

  def initialize
    @date = "%s"
    @commit_number = %d
    @total_commits = %d
  end

  def info
    "Contribution on #{date} (#{commit_number}/#{total_commits})"
  end
  
  def to_s
    info
  end
end

if __FILE__ == $0
  contribution = Contribution.new
  puts contribution.info
end
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *RubyTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Ruby project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Ruby contribution records.\n\n## Structure\n\n- `lib/` - Ruby source files\n- `Gemfile` - Ruby dependencies\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *RubyTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"Gemfile": `source 'https://rubygems.org'

# Add your dependencies here
`,
		".gitignore": `Gemfile.lock
.bundle/
vendor/
.idea/
.vscode/
`,
	}
}
