package languages

import (
	"fmt"
	"strings"
)

// RustTemplate Rust模板
type RustTemplate struct{}

func (t *RustTemplate) GetFileExtension() string     { return ".rs" }
func (t *RustTemplate) GetActivityFileName() string  { return "activity.rs" }
func (t *RustTemplate) GetLanguageName() string      { return "Rust" }

func (t *RustTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	_ = fmt.Sprintf("contribution_%s_%d", strings.ReplaceAll(date, "-", "_"), commitNum)
	return fmt.Sprintf(`//! Contribution record for %s
//! Commit %d of %d
//! Generated by GreenWall

/// Represents a single contribution record
pub struct Contribution {
    date: String,
    commit_number: u32,
    total_commits: u32,
}

impl Contribution {
    /// Creates a new Contribution instance
    pub fn new() -> Self {
        Contribution {
            date: "%s".to_string(),
            commit_number: %d,
            total_commits: %d,
        }
    }
    
    /// Returns contribution information
    pub fn get_info(&self) -> String {
        format!("Contribution on {} ({}/{})", self.date, self.commit_number, self.total_commits)
    }
}

impl Default for Contribution {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_contribution() {
        let contribution = Contribution::new();
        assert_eq!(contribution.date, "%s");
    }
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits, date)
}

func (t *RustTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Rust project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Rust contribution records.\n\n## Structure\n\n- `src/` - Rust source files\n- `Cargo.toml` - Rust package manifest\n- `README.md` - This file\n\n## Build\n\n```bash\ncargo build\n```\n\n## Test\n\n```bash\ncargo test\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *RustTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"Cargo.toml": fmt.Sprintf(`[package]
name = "%s"
version = "1.0.0"
edition = "2021"

[dependencies]
`, repoName),
		".gitignore": `# Rust
target/
Cargo.lock
**/*.rs.bk
*.pdb

# IDE
.vscode/
.idea/
*.swp
`,
	}
}
