package languages

import (
	"fmt"
)

// SCSSTemplate SCSS模板
type SCSSTemplate struct{}

func (t *SCSSTemplate) GetFileExtension() string     { return ".scss" }
func (t *SCSSTemplate) GetActivityFileName() string  { return "style.scss" }
func (t *SCSSTemplate) GetLanguageName() string      { return "SCSS" }

func (t *SCSSTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`// Contribution record for %s
// Commit %d of %d
// Generated by GreenWall

$date: "%s";
$commit-num: %d;
$total-commits: %d;

.contribution-#{$date}-#{$commit-num} {
    @mixin card {
        display: block;
        background-color: #f6f8fa;
        border: 1px solid #d1d5da;
        border-radius: 3px;
        padding: 8px 16px;
    }

    @include card;
    
    &::before {
        content: "Contribution on #{$date}";
        font-weight: bold;
    }

    &::after {
        content: "Commit #{$commit-num}/#{$total-commits}";
        color: #586069;
        font-size: 0.9em;
    }
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *SCSSTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA SCSS project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated SCSS contribution records.\n\n## Structure\n\n- `styles/` - SCSS files\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *SCSSTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		".gitignore": `.DS_Store
.sass-cache/
*.css
*.css.map
.vscode/
.idea/
`,
	}
}
