package languages

import (
	"fmt"
)

// ShellTemplate Shell模板
type ShellTemplate struct{}

func (t *ShellTemplate) GetFileExtension() string     { return ".sh" }
func (t *ShellTemplate) GetActivityFileName() string  { return "activity.sh" }
func (t *ShellTemplate) GetLanguageName() string      { return "Shell" }

func (t *ShellTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`#!/bin/bash
# Contribution record for %s
# Commit %d of %d
# Generated by GreenWall

DATE="%s"
COMMIT_NUM=%d
TOTAL_COMMITS=%d

echo "Contribution on $DATE ($COMMIT_NUM/$TOTAL_COMMITS)"
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *ShellTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA Shell script collection generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated Shell contribution records.\n\n## Structure\n\n- `scripts/` - Shell scripts\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *ShellTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		".gitignore": `.DS_Store
*.log
.vscode/
.idea/
`,
	}
}
