package languages

import (
	"fmt"
)

// SQLTemplate SQL模板
type SQLTemplate struct{}

func (t *SQLTemplate) GetFileExtension() string     { return ".sql" }
func (t *SQLTemplate) GetActivityFileName() string  { return "activity.sql" }
func (t *SQLTemplate) GetLanguageName() string      { return "SQL" }

func (t *SQLTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`-- Contribution record for %s
-- Commit %d of %d
-- Generated by GreenWall

INSERT INTO contributions (date, commit_number, total_commits)
VALUES ('%s', %d, %d);
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *SQLTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA SQL script collection generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated SQL contribution records.\n\n## Structure\n\n- `scripts/` - SQL scripts\n- `README.md` - This file\n\n## License\n\nMIT License\n", repoName)
}

func (t *SQLTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"schema.sql": `CREATE TABLE IF NOT EXISTS contributions (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    commit_number INT NOT NULL,
    total_commits INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`,
		".gitignore": `*.db
*.sqlite
*.log
.vscode/
.idea/
`,
	}
}
