package languages

import (
	"fmt"
)

// TypeScriptTemplate TypeScript模板
type TypeScriptTemplate struct{}

func (t *TypeScriptTemplate) GetFileExtension() string     { return ".ts" }
func (t *TypeScriptTemplate) GetActivityFileName() string  { return "activity.ts" }
func (t *TypeScriptTemplate) GetLanguageName() string      { return "TypeScript" }

func (t *TypeScriptTemplate) GenerateCode(date string, commitNum int, totalCommits int) string {
	return fmt.Sprintf(`/**
 * Contribution record for %s
 * Commit %d of %d
 * Generated by GreenWall
 */

interface ContributionInfo {
  date: string;
  commitNumber: number;
  totalCommits: number;
}

class Contribution implements ContributionInfo {
  public readonly date: string = '%s';
  public readonly commitNumber: number = %d;
  public readonly totalCommits: number = %d;

  getInfo(): string {
    return ` + "`Contribution on ${this.date} (${this.commitNumber}/${this.totalCommits})`" + `;
  }

  toString(): string {
    return this.getInfo();
  }
}

export default Contribution;

// If running directly
if (require.main === module) {
  const contribution = new Contribution();
  console.log(contribution.getInfo());
}
`, date, commitNum, totalCommits, date, commitNum, totalCommits)
}

func (t *TypeScriptTemplate) GetReadmeContent(repoName string) string {
	return fmt.Sprintf("# %s\n\nA TypeScript project generated with [GreenWall](https://github.com/Cail-Gainey/GreenWall).\n\n## About\n\nThis repository contains automatically generated TypeScript contribution records.\n\n## Structure\n\n- `src/` - TypeScript source files\n- `package.json` - Node.js package configuration\n- `tsconfig.json` - TypeScript configuration\n- `README.md` - This file\n\n## Installation\n\n```bash\nnpm install\n```\n\n## Build\n\n```bash\nnpm run build\n```\n\n## License\n\nMIT License\n", repoName)
}

func (t *TypeScriptTemplate) GetAdditionalFiles(repoName string) map[string]string {
	return map[string]string{
		"package.json": fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "description": "Generated with GreenWall",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": ["greenwall", "contributions", "typescript"],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0"
  }
}
`, repoName),
		"tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`,
		".gitignore": `node_modules/
dist/
npm-debug.log
yarn-error.log
.env
.DS_Store
*.tsbuildinfo
.vscode/
.idea/
`,
	}
}
